version: '2'
services:
    contractmono-app:
        image: contractmono
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://contractmono-mysql:3306/contractmono?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    contractmono-mysql:
        extends:
            file: mysql.yml
            service: contractmono-mysql
